fifa/urls.py
from django.contrib import admin
from django.urls import path, include
from fifapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fifapp.urls')), 
    path('crear_equipo/', views.crear_equipo, name='crear_equipo'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fifapp/urls.py
# fifapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('login/index', views.index, name='index'), 
    path('crear_equipo/', views.crear_equipo, name='crear_equipo'),
    path('crear_posicion_juego/', views.crear_posicion_juego, name='crear_posicion_juego'),
    path('listar_posiciones_juego/', views.listar_posiciones_juego, name='listar_posiciones_juego'),
    path('crear_tecnico/', views.crear_tecnico, name='crear_tecnico'),
    path('crear_jugador/', views.crear_jugador, name='crear_jugador'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),    
]

fifapp/models.py
from django.db import models
# Create your models here.


class Equipo(models.Model):
    nombre = models.CharField(max_length=255)
    imagen_bandera = models.ImageField(upload_to='banderas/')
    escudo_equipo = models.ImageField(upload_to='escudos/')

    def __str__(self):
        return self.nombre

class PosicionJuego(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre



class Jugador(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='jugadores/')
    fecha_nacimiento = models.DateField()
    posicion = models.ForeignKey(PosicionJuego, on_delete=models.CASCADE)
    numero_camiseta = models.IntegerField()
    titular = models.BooleanField(default=False)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)  

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

    
    
class Tecnico(models.Model):
    ROLES_CHOICES = [
        ('Técnico', 'Técnico'),
        ('Asistente', 'Asistente'),
        ('Médico', 'Médico'),
        ('Preparador Físico', 'Preparador Físico'),
    ]
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    nacionalidad = models.CharField(max_length=100)
    rol = models.CharField(max_length=20, choices=ROLES_CHOICES)
    

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

fifapp/forms.py
from django import forms
from .models import Equipo, PosicionJuego, Tecnico, Jugador
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ['nombre', 'imagen_bandera', 'escudo_equipo']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'imagen_bandera': forms.FileInput(attrs={'class': 'form-control-file'}),
            'escudo_equipo': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

class PosicionJuegoForm(forms.ModelForm):
    class Meta:
        model = PosicionJuego
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
        }
        

class TecnicoForm(forms.ModelForm):
    class Meta:
        model = Tecnico
        fields = ['nombre', 'apellido', 'fecha_nacimiento', 'nacionalidad', 'rol']
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
        }


class JugadorForm(forms.ModelForm):
    class Meta:
        model = Jugador
        fields = ['nombre', 'apellido', 'foto', 'fecha_nacimiento', 'posicion', 'numero_camiseta', 'titular', 'equipo']
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
        }

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'User name / Email', 'class': 'Login-input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password', 'class': 'Login-input'}))

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

fifapp/views.py
from django.shortcuts import render, redirect
from .forms import EquipoForm, PosicionJuegoForm, TecnicoForm, JugadorForm, LoginForm, CustomUserCreationForm
from .models import Equipo, PosicionJuego, Tecnico, Jugador
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse


def crear_equipo(request):
    if request.method == 'POST':
        form = EquipoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('crear_equipo')
    else:
        form = EquipoForm()

    equipos = Equipo.objects.all()  
    return render(request, 'fifapp/crear_equipo.html', {'form': form, 'equipos': equipos})  

def crear_posicion_juego(request):
    if request.method == 'POST':
        form = PosicionJuegoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index') 
    else:
        form = PosicionJuegoForm()  
    return render(request, 'fifapp/crear_posicion_juego.html', {'form': form})

def listar_posiciones_juego(request):
    posiciones_juego = PosicionJuego.objects.all()
    return render(request, 'fifapp/listar_posiciones_juego.html', {'posiciones_juego': posiciones_juego})


def crear_tecnico(request):
    if request.method == 'POST':
        form = TecnicoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crear_tecnico')
    else:
        form = TecnicoForm()

    tecnicos = Tecnico.objects.all()
    return render(request, 'fifapp/crear_tecnico.html', {'form': form, 'tecnicos': tecnicos})


def crear_jugador(request):
    if request.method == 'POST':
        form = JugadorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('crear_jugador')
    else:
        form = JugadorForm()

    jugadores = Jugador.objects.all() 
    return render(request, 'fifapp/crear_jugador.html', {'form': form, 'jugadores': jugadores})


def index(request):
    equipos = Equipo.objects.all()
    jugadores = Jugador.objects.all()
    tecnicos = Tecnico.objects.all()
    return render(request, 'fifapp/index.html', {'equipos': equipos, 'jugadores': jugadores, 'tecnicos': tecnicos})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('index')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'fifapp/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'fifapp/register.html', {'form': form})

fifapp/templates/fifapp/crear_equipo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Crear Equipo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/formularios.css' %}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">FIFA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'crear_jugador' %}">Jugadores</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'crear_equipo' %}">Equipos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'crear_tecnico' %}">Tecnicos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Ingresar</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
                </li>
                
              </ul>
            </div>
          </div>
        </nav>
        </header>
    <h2>Crear Equipo</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <hr>
    
    <div class="container">
        <section id="equipos" class="mt-5">
          <h2>Equipos</h2>
          <div class="row">
            {% for equipo in equipos %}
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{ equipo.nombre }}</h5>
                  <img src="{{ equipo.escudo_equipo.url }}" class="card-img-top" alt="{{ equipo.nombre }} Escudo">
                  <img src="{{ equipo.imagen_bandera.url }}" class="card-img-top" alt="{{ equipo.nombre }} Bandera">
                  <ul>
                    {% for jugador in equipo.jugador_set.all %}
                    <li>{{ jugador.nombre }} {{ jugador.apellido }} - {{ jugador.posicion }} - Titular: {% if jugador.titular %}Sí{% else %}No{% endif %}</li>
                    {% empty %}
                    <li>No hay jugadores registrados para este equipo.</li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
            {% empty %}
            <p class="col">No hay equipos registrados.</p>
            {% endfor %}
          </div>
        </section>
</body>
<footer class="mt-5">
    <p>© 2022 Página de Fútbol</p>
</footer>
</html>

fifapp/templates/fifapp/crear_jugador.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Jugador</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/formularios.css' %}">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">FIFA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'crear_jugador' %}">Jugadores</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'crear_equipo' %}">Equipos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'crear_tecnico' %}">Tecnicos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Ingresar</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
                </li>
                
              </ul>
            </div>
          </div>
        </nav>
        </header>
    <h2>Crear Jugador</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <div class="container">
        <section id="jugadores" class="jugadores-section mt-5">
          <h2>Jugadores</h2>
          <div class="row">
            {% for jugador in jugadores %}
            <div class="col-md-4 mb-3">
              <div class="card">
                <img src="{{ jugador.foto.url }}" class="card-img-top" alt="{{ jugador.nombre }} {{ jugador.apellido }}">
                <div class="card-body">
                  <h5 class="card-title">{{ jugador.nombre }} {{ jugador.apellido }}</h5>
                  <p class="card-text">Fecha de Nacimiento: {{ jugador.fecha_nacimiento }}</p>
                  <p class="card-text">Posición: {{ jugador.posicion.nombre }}</p>
                  <p class="card-text">Número de camiseta: {{ jugador.numero_camiseta }}</p>
                  <p class="card-text">Titular: {% if jugador.titular %} Sí {% else %} No {% endif %}</p>
                  <p class="card-text">Equipo: {{ jugador.equipo.nombre }}</p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </section>
      </div>
</body>
<footer class="mt-5">
    <p>© 2022 Página de Fútbol</p>
</footer>
</html>

fifapp/templates/fifapp/crear_posicion_juego.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Posición de Juego</title>
</head>
<body>
    <h2>Crear Posición de Juego</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>

fifapp/templates/fifapp/crear_tecnico.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Técnico</title>
    <link rel="stylesheet" href="{% static 'css/formularios.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">FIFA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crear_jugador' %}">Jugadores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crear_equipo' %}">Equipos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crear_tecnico' %}">Tecnicos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Ingresar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
            </li>
            
          </ul>
        </div>
      </div>
    </nav>
    </header>
    <h2>Crear Técnico</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>

    <section id="tecnico" class="mt-5">
      <h2 >Técnicos</h2>
      <div class="row">
        {% for tecnico in tecnicos %}
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ tecnico.nombre }} {{ tecnico.apellido }}</h5>
              <p class="card-text">Rol: {{ tecnico.rol }}</p>
              <p class="card-text">Nacionalidad: {{ tecnico.nacionalidad }}</p>
            </div>
          </div>
        </div>
        {% empty %}
        <p class="col">No hay técnicos registrados.</p>
        {% endfor %}
      </div>
    </section>    
</body>
<footer class="mt-5">
  <p>© 2022 Página de Fútbol</p>
</footer>
</html>

fifapp/templates/fifapp/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Formulario de Equipo</title>
</head>
<body>
    <h1>Crear Equipo</h1>
    <form action="/crear_equipo/" method="post">
        {% csrf_token %}
        <label for="nombre_equipo">Nombre del equipo:</label>
        <input type="text" id="nombre_equipo" name="nombre_equipo" required>
        <br>
        <label for="imagen_bandera">Imagen de la bandera (URL):</label>
        <input type="url" id="imagen_bandera" name="imagen_bandera" required>
        <br>
        <label for="escudo_equipo">Escudo del equipo (URL):</label>
        <input type="url" id="escudo_equipo" name="escudo_equipo" required>
        <br>
        <button type="submit">Crear equipo</button>
    </form>

     <!-- Lista de Equipos -->
     <h2>Listado de Equipos</h2>
     <ul>
         {% for equipo in equipos %}
             <li>
                 <h3>{{ equipo.nombre }}</h3>
                 <img src="{{ equipo.imagen_bandera.url }}" alt="Bandera de {{ equipo.nombre }}">
                 <img src="{{ equipo.escudo_equipo.url }}" alt="Escudo de {{ equipo.nombre }}">
             </li>
         {% empty %}
             <li>No hay equipos registrados.</li>
         {% endfor %}
     </ul>
</body>
</html>

fifapp/templates/fifapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Página de Fútbol</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">FIFA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crear_jugador' %}">Jugadores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crear_equipo' %}">Equipos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crear_tecnico' %}">Tecnicos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Ingresar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
            </li>
            
          </ul>
        </div>
      </div>
    </nav>
    </header>
    <nav>
      <div id="carouselExampleCaptions" class="carousel slide">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'images/dinho.jpg' %}"style="width: 100%;" alt="">
            <div class="carousel-caption d-none d-md-block">
              <p>Consulta aqui tus Jugadores favoritos</p>
              <a href="#jugadores">Jugadores</a>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/col.jpg' %}" style="width: 100%;" alt="">
            <div class="carousel-caption d-none d-md-block">
              <p>Consulta aqui tus Equipos favoritos</p>
              <a href="#equipos">Equipos</a>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/españa.jpg' %}" style="width: 100%;" alt="">
            <div class="carousel-caption d-none d-md-block">
              <p>Consulta aqui hacerca de tus Entrenadores favoritos</p>
              <a href="#tecnico">Entrenadores</a>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </nav>
    <div class="container">
      <section id="jugadores" class="jugadores-section mt-5">
        <h2>Jugadores</h2>
        <a href="{% url 'crear_jugador' %}" class="btn btn-primary mb-3">Agregar Jugador</a>
        <div class="row">
          {% for jugador in jugadores %}
          <div class="col-md-4 mb-3">
            <div class="card">
              <img src="{{ jugador.foto.url }}" class="card-img-top" alt="{{ jugador.nombre }} {{ jugador.apellido }}">
              <div class="card-body">
                <h5 class="card-title">{{ jugador.nombre }} {{ jugador.apellido }}</h5>
                <p class="card-text">Fecha de Nacimiento: {{ jugador.fecha_nacimiento }}</p>
                <p class="card-text">Posición: {{ jugador.posicion.nombre }}</p>
                <p class="card-text">Número de camiseta: {{ jugador.numero_camiseta }}</p>
                <p class="card-text">Titular: {% if jugador.titular %} Sí {% else %} No {% endif %}</p>
                <p class="card-text">Equipo: {{ jugador.equipo.nombre }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </section>
    </div>
    
  <div class="container">
    <section id="equipos" class="mt-5">
      <h2>Equipos</h2>
      <a href="{% url 'crear_equipo' %}" class="btn btn-primary mb-3">Agregar equipo</a>
      <div class="row">
        {% for equipo in equipos %}
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ equipo.nombre }}</h5>
              <img src="{{ equipo.escudo_equipo.url }}" class="card-img-top" alt="{{ equipo.nombre }} Escudo">
              <img src="{{ equipo.imagen_bandera.url }}" class="card-img-top" alt="{{ equipo.nombre }} Bandera">
              <ul>
                {% for jugador in equipo.jugador_set.all %}
                <li>{{ jugador.nombre }} {{ jugador.apellido }} - {{ jugador.posicion }} - Titular: {% if jugador.titular %}Sí{% else %}No{% endif %}</li>
                {% empty %}
                <li>No hay jugadores registrados para este equipo.</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        {% empty %}
        <p class="col">No hay equipos registrados.</p>
        {% endfor %}
      </div>
    </section>
  
    <section id="tecnico" class="mt-5">
      <h2 >Técnicos</h2>
      <a href="{% url 'crear_tecnico' %}" class="btn btn-primary mb-3">Agregar equipo</a>
      <div class="row">
        {% for tecnico in tecnicos %}
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ tecnico.nombre }} {{ tecnico.apellido }}</h5>
              <p class="card-text">Rol: {{ tecnico.rol }}</p>
              <p class="card-text">Nacionalidad: {{ tecnico.nacionalidad }}</p>
            </div>
          </div>
        </div>
        {% empty %}
        <p class="col">No hay técnicos registrados.</p>
        {% endfor %}
      </div>
    </section>
  </div>
<footer class="mt-5">
      <p>© 2022 Página de Fútbol</p>
</footer>
</html>

  

fifapp/templates/fifapp/listar_jugadores.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado de Jugadores</title>
</head>
<body>
    <h2>Listado de Jugadores</h2>
    <ul>
        {% for jugador in jugadores %}
            <li>{{ jugador.nombre }} {{ jugador.apellido }} - {{ jugador.posicion }} - Titular: {% if jugador.titular %}Sí{% else %}No{% endif %}</li>
        {% empty %}
            <li>No hay jugadores registrados.</li>
        {% endfor %}
    </ul>
</body>
</html>

fifapp/templates/fifapp/listar_posiciones_juego.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado de Posiciones de Juego</title>
</head>
<body>
    <h2>Listado de Posiciones de Juego</h2>
    <ul>
        {% for posicion_juego in posiciones_juego %}
            <li>{{ posicion_juego.nombre }} - {{ posicion_juego.descripcion }}</li>
        {% empty %}
            <li>No hay posiciones de juego registradas.</li>
        {% endfor %}
    </ul>
</body>
</html>

fifapp/templates/fifapp/listar_tecnicos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado de Técnicos</title>
</head>
<body>
    <h2>Listado de Técnicos</h2>
    <ul>
        {% for tecnico in tecnicos %}
            <li>{{ tecnico.nombre }} {{ tecnico.apellido }} - {{ tecnico.rol }}</li>
        {% empty %}
            <li>No hay técnicos registrados.</li>
        {% endfor %}
    </ul>
</body>
</html>